pom.xml
src/main/java/de/retest/web/AttributesProvider.java
src/test/java/de/retest/web/AttributesProviderTest.java
src/test/java/de/retest/web/CheckRetestWebsite.java
src/test/java/de/retest/web/RecheckSeleniumAdapterTest.java

Let's see if this is enough to reach 50% coverage… 😉
Please also check the `TODO` note.

Address quality gate

---

README.md
pom.xml
src/test/java/de/retest/web/SimplePageIT.java

What we need for the SCC workshop, including a new recheck-web release.

Upgrade recheck

---

src/main/java/de/retest/web/AttributesConfigLoadException.java
src/main/java/de/retest/web/AttributesProvider.java
src/main/java/de/retest/web/RecheckSeleniumAdapter.java

since you cannot read a file from jar
Who does this anyway?
How can we test this?

Use getResourceAsStream instead of file

---

src/main/resources/attributes.yaml

{clip = [expected=rect(0px, 0px, 0px, 0px), actual=rect(0px 0px 0px 0px)]}

Clip was chosen more or less randomly and is giving us a headache with

---

pom.xml
src/test/resources/retest/recheck/de.retest.web.SimplePageIT/simple-page.open.recheck/retest.xml

This now also runs JUnit 5-based integration tests. (Why did I miss the update on the update branch?)

Update Failsafe plugin

---

src/main/java/de/retest/web/DefaultValuesProvider.java
src/test/java/de/retest/web/DefaultValuesProviderTest.java
src/test/resources/retest/recheck/de.retest.web.ShowcaseIT/showcase.index.recheck/retest.xml

- Fix method isDefault
- Add some tests to check the default values correctly
- Delete the unneeded defaults from the retest.xml
With the fix it should be possible that no default values are written to the retest.xml

Fix method isDefault

---

pom.xml

Could you please also deploy on Sonatype?

Release v0.4.0

---

.travis.yml

- Update travis-ci to automatically upload our golden masters to s3 digital-ocean-space

upload-artifacts

---

README.md

Remove trademarks

---

.travis.yml
src/test/java/de/retest/web/testutils/WebDriverFactory.java

@kema91 would you mind removing `sudo: false` from all other repos that have a `.travis.yml`?

Clean up travis yml

---

pom.xml

Update to latest version

---

ci/script.sh

See https://community.sonarsource.com/t/travis-plugin-is-failing-on-external-pull-request/807/3.

Add SonarCloud workaround for external PRs

---

README.md
pom.xml
src/test/java/de/retest/web/it/WikipediaIT.java

Draft: Wait for recheck v0.20.0 (or v1.0.0).

Rename test report

---

src/main/java/de/retest/web/RecheckSeleniumAdapter.java
src/main/java/de/retest/web/ScreenshotProvider.java

Documention: https://github.com/retest/docs/pull/14.

Enable viewport only screenshot

---

src/main/java/de/retest/web/AttributesConfig.java
src/main/java/de/retest/web/AttributesProvider.java
src/main/java/de/retest/web/AttributesUtil.java
src/main/java/de/retest/web/PeerConverter.java
src/main/java/de/retest/web/RecheckSeleniumAdapter.java
src/main/java/de/retest/web/RootElementPeer.java
src/main/java/de/retest/web/WebElementPeer.java
src/main/java/de/retest/web/YamlAttributesConfig.java
src/main/java/de/retest/web/YamlAttributesConfigDeserializer.java
src/main/java/de/retest/web/YamlAttributesProvider.java
src/test/java/de/retest/web/AttributesUtilTest.java
src/test/java/de/retest/web/WebElementPeerTest.java
src/test/java/de/retest/web/YamlAttributesConfigDeserializerTest.java
src/test/java/de/retest/web/YamlAttributesProviderTest.java

Allow custom providers for RecheckSeleniumAdapter

---

src/main/java/de/retest/web/PeerConverter.java
src/main/java/de/retest/web/RecheckSeleniumAdapter.java
src/main/java/de/retest/web/RootElementPeer.java
src/main/java/de/retest/web/WebElementPeer.java
src/main/java/de/retest/web/mapping/PathsToWebDataMapping.java
src/main/java/de/retest/web/mapping/WebData.java
src/main/java/de/retest/web/mapping/WebDataFilter.java
src/test/java/de/retest/web/PeerConverterTest.java
src/test/java/de/retest/web/WebElementPeerTest.java
src/test/java/de/retest/web/mapping/WebDataFilterTest.java
src/test/java/de/retest/web/mapping/WebDataTest.java

Introduces a lightweight wrapper for our initial mapping of raw web data.

Refactor raw mapping

---

ci/script.sh
pom.xml

Basically same as in recheck, resolves https://github.com/retest/recheck/issues/150.

Compile with 8 and test with 11

---

pom.xml

Then others can show the contained recheck version.

Add default manifest entries

---

pom.xml

Revert "Bump jackson.version from 2.9.9 to 2.10.0.pr1"

---

.retest/recheck.ignore
.retest/recheck.ignore.js
src/test/java/de/retest/web/it/RecheckIgnoreJsIT.java

We now have a native solution for this.

Simplify ignore

---

src/main/java/de/retest/web/selenium/WebElementWrapper.java

This is a commit that inputs the code from https://github.com/javydreamercsw
of PR https://github.com/retest/recheck-web/pull/289/ and addresses issue https://github.com/retest/recheck-web/issues/288

Exposing wrapped WebElement

---

src/main/java/de/retest/web/selenium/WebElementWrapper.java

Should solve issue https://github.com/retest/recheck-web/issues/290

When we added the method, we also should have added the marker interface

---

README.md

See https://docs.retest.de/recheck-web/tutorial/upload-test-reports-to-rehub/.

Sync readme with current docs

---

README.md

- Add link to Chrome extension
- Change `RecheckDriver` to `UnbreakableDriver` (first one is autochecking)
- Add short explanation how "unkreakable" works

Improve readme in various ways

---

src/main/java/de/retest/web/RecheckWebImpl.java

https://github.com/retest/recheck-web/issues/326#issuecomment-531258603

Thanks to the feedback in #326, we need to improve error handling

---

pom.xml

Should turn green as soon as the beta is available on central.

Bump recheck

---

src/main/java/de/retest/web/RecheckSeleniumAdapter.java
src/main/java/de/retest/web/selenium/UnbreakableDriver.java
src/main/java/de/retest/web/util/SeleniumWrapperUtil.java
src/test/java/de/retest/web/RecheckSeleniumAdapterTest.java
src/test/java/de/retest/web/selenium/UnbreakableDriverTest.java
src/test/java/de/retest/web/util/SeleniumWrapperUtilTest.java

Please review carefully, I feel dirty …

Fix wrappers

---

src/main/resources/javascript/getAllElementsByPath.js

First of a couple of PRs to unify the two getAllElements.js files. This one is not critical—rest after 1.6.0.

Feature/unify get all elements by path.js

---

README.md

Making the text more accurate, as only wrapping does not suffice

---

src/main/java/de/retest/web/selenium/NoElementWithHighEnoughMatchFoundException.java

This is a very simple PR, that only changes the text of an exception. I deem no test should be adapted for this, and I don't think it warrants a changelog entry or documentation change.

Improve message to be actionable for users

---

.retest/recheck.ignore.js
src/test/java/de/retest/web/it/RecheckIgnoreJsIT.java

Diff can be null, but given objects are immutable

---

src/main/java/de/retest/web/selenium/TestHealer.java

Simplify code after method is available

---

pom.xml

This now includes a recheck snapshot based on this commit:
https://github.com/retest/recheck/commit/7753f2e258c4d0fe5eddbc9df15ddaa08bf44a87
We can easily switch to a different commit if we need other changes.
During a release, we then switch to a recent beta.

Include recheck snapshot via JitPack

---

src/main/java/de/retest/web/RecheckWebProperties.java

Refactor property to how it is documented

---

src/main/java/de/retest/web/meta/SeleniumMetadata.java
src/main/java/de/retest/web/meta/driver/WebDriverMetadataProvider.java
src/test/java/de/retest/web/it/SimplePageDiffIT.testSimpleChange.approved.txt

window.width and window.height are not driver specific properties

---

ci/before.sh

Updated the geckodriver from v0.24.0 to the current v0.26.0
All done.
I wanted this to break tests so that I'd have a clearer idea what to do about updating Travis CI to use `bionic`, but well everything worked fine ;-)

Update geckodriver to latest version (v0.26.0)

---

README.md

Just noticed a missing word. Additionally I wanted to avoid using 'easily' twice in the same sentence.
All done.

Missing word in README, minor wording nitpick

---

pom.xml
src/main/java/de/retest/web/selenium/By.java

Simply update dependency to find problems early on, and not during release...

Update recheck to intermediate version to find errors early

---

CHANGELOG.md
src/main/java/de/retest/web/RecheckWebOptions.java
src/main/java/de/retest/web/screenshot/ScreenshotProviders.java

See also https://github.com/retest/docs/pull/79.

Allow to locally enable/disable screenshots, e.g. for GM creation

---

CHANGELOG.md

Finalize changelog for release 1.8.1

---

pom.xml

Was on the wrong branch... sigh

Bump recheck version to 1.9.0-beta.1

---

src/main/resources/javascript/getAllElementsByPath.js

This is a pure refactoring and thus should have no conceivable effect from the outside.

Rename variable to parent, because this is what it is semantically

---

CHANGELOG.md
src/main/java/de/retest/web/RecheckSeleniumAdapter.java
src/main/java/de/retest/web/RecheckWebOptions.java
src/main/java/de/retest/web/RecheckWebProperties.java
src/test/java/de/retest/web/RecheckWebImplIT.java

Fixes #523.
Any idea for a good test case? Some integration between `RecheckWebOptions` and `RecheckSeleniumAdapter`.
Also, build fails due to #524 and changelog needs to be updated.

Fix screenshots

---

pom.xml

As we discussed: Include selenium-java instead of each dependency. Just forgot about it...

Include the whole package

---

CHANGELOG.md
src/main/java/de/retest/web/RecheckWebOptions.java

This reverts commit f2eb41ba02753b8ca5f20521ba0db10280dce8f8 partially.

Revert "Fix visibility"

---

CHANGELOG.md

Can you think of a better changelog message?

Prepare changelog for 1.10.2

---

src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimplePageDiffIT/testSimpleChange.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimplePageIT/simple-page-ChromeDriver.open.recheck/retest.xml

By updating GMs with new Chrome defaults. Again, addressing #332 would be really helpful.

Fix master

---

CHANGELOG.md
src/main/java/de/retest/web/FrameConverter.java
src/main/java/de/retest/web/RecheckSeleniumAdapter.java
src/main/java/de/retest/web/mapping/PathsToWebDataMapping.java
src/main/resources/javascript/getAllElementsByPath.js
src/test/java/de/retest/web/PeerConverterTest.java
src/test/java/de/retest/web/RecheckSeleniumAdapterTest.java
src/test/java/de/retest/web/mapping/PathsToWebDataMappingTest.java

Preserve the order of the elements in the HTML structure

---

src/test/resources/retest/recheck/de.retest.web.RecheckSeleniumAdapterIT/warnings_should_be_notified_properly_on_breaking_change.a.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.RecheckSeleniumAdapterIT/warnings_should_be_notified_properly_on_breaking_change.b.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.RecheckSeleniumAdapterIT/warnings_should_be_notified_properly_on_breaking_change.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.CenterIT/center-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.FormPageIT/form-page-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementFailingIT/select-element-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementFailingIT/select-element-FirefoxDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/findElement-equals-driver-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.ShowcaseIT/showcase-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.00.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.01.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.02.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.03.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.04.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.05.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimplePageDiffIT/testSimpleChange.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimplePageIT/simple-page-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleRecheckShowcaseIT/simpleShowcase.index.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerIT/special-container-ChromeDriver.click.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerIT/special-container-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.TestHealerCssSelectorIT/setup.00.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.TestHealerCssSelectorIT/setup.01.recheck/retest.xml

Apparently, chrome updated once again... Hmm, just noticing. Shoudn't the metadata update correspondingly?

Update Golden Masters

---

CHANGELOG.md
src/main/java/de/retest/web/meta/SeleniumMetadata.java
src/main/java/de/retest/web/meta/driver/capabilities/PlatformMetadataProvider.java

TL;DR: We need to always override the system metadata, so that we do not mix it...

Always override the system ones, so that we do not end up with mixed info

---

.retest/retest.properties

since rehub seems to be offline now

Disable rehub upload

---

CHANGELOG.md
src/main/java/de/retest/web/RecheckWebOptions.java
src/main/java/de/retest/web/selenium/AutocheckingRecheckDriver.java
src/test/resources/retest/recheck/de.retest.web.it.FormPageIT/form-page-FirefoxDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-FirefoxDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/findElement-equals-driver-FirefoxDriver.open.recheck/retest.xml

Add Option for autochecking delay
finished

Add Option for autochecking delay

---

src/test/resources/retest/recheck/de.retest.web.it.FormPageIT/form-page-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/findElement-equals-driver-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.ShowcaseIT/showcase-FirefoxDriver.open.recheck/retest.xml

add some accepted changes in tests
