retest/recheck-web

.travis.yml

We skip the install phase, so it's probably better here.

Move signing to script phase

---

.gitignore
src/test/java/de/retest/web/ShowcaseIT.java
src/test/java/de/retest/web/testutils/ChromeOptionsFactory.java

Removed the property from the `ChromeOptionsFactory` because I thought it is more about making the showcase run, not the entire project (which requires ChromeDriver to be in PATH anyway).

Add optional system property for ChromeDriver

---

src/test/resources/retest/retest.properties

We don't have to set this. The property from `CheckAccessFileImpl` is only used internally to see if a custom recheck directory is desired. If we need the property generally is separate discussion. However, for now, less properties mean less confusion.

Remove property

---

src/main/java/de/retest/web/RecheckWebImpl.java

Needs the possibility to pass options since only the default ctor is inherited. (See also #169.)

Add missing ctor

---

src/main/java/de/retest/web/WebElementPeer.java
src/test/java/de/retest/web/WebElementPeerTest.java

I tested different sites and html files and i saw, that the attribute changes are shown twice when we only test the "retest.de" site. Actually the attributes are the same and one of them is not showed in the attribute field.
With the filter in the WebElementPeer.java class  i fixed that and the attribute occurs only one time:

The problem - some attribute changes show up twice no longer occurs

---

src/main/java/de/retest/web/PeerConverter.java
src/main/java/de/retest/web/RecheckSeleniumAdapter.java
src/main/java/de/retest/web/RootElementPeer.java
src/main/java/de/retest/web/WebElementPeer.java
src/test/java/de/retest/web/WebElementPeerTest.java

We cannot use a static reference, this causes e.g. in surili that two different retest ID providers are being used—the one being passed to `RecheckSeleniumAdapter` and the globally configured.
Thinking about a hotfix for this … waiting for yet another release slows surili development down. Or we finally start with nightlies.
Oh and better look at it commit-wise, second commit produces ugly diffs due to formatting changes.

Fix retest ID provider usage

---

src/main/java/de/retest/web/YamlAttributesConfig.java
src/main/java/de/retest/web/selenium/AutocheckingCheckNamingStrategy.java
src/main/java/de/retest/web/selenium/AutocheckingRecheckDriver.java
src/main/java/de/retest/web/selenium/RecheckDriver.java
src/main/java/de/retest/web/selenium/UnbreakableDriver.java

Document all main driver classes and avoid redundancy.
Resolves #262 along with https://github.com/retest/docs/pull/27.

Improve Javadoc

---

src/main/java/de/retest/web/FrameConverter.java
src/main/java/de/retest/web/RecheckSeleniumAdapter.java
src/test/resources/pages/special-container.html
src/test/resources/retest/recheck/de.retest.web.it.ShowcaseIT/showcase-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.ShowcaseIT/showcase-FirefoxDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleRecheckShowcaseIT/simple-showcase.index.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerTestIT/special-container-ChromeDriver.click.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerTestIT/special-container-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerTestIT/special-container-FirefoxDriver.click.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerTestIT/special-container-FirefoxDriver.open.recheck/retest.xml

We are currently limited to frames that have an ID (see https://github.com/retest/recheck-web/blob/master/src/main/java/de/retest/web/RecheckSeleniumAdapter.java#L96). This PR is intended to support all kind of IFrames, i.e., without an ID, a name or something else.
I've marked this as a draft because it is untested, somewhat blocked by #295.

Support more IFrames

---

src/main/java/de/retest/web/ScreenshotProvider.java
src/test/java/de/retest/web/ScreenshotProviderTest.java

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.assertthat.selenium_shutterbug.utils.web.Browser.sendCommand(Browser.java:276)
at com.assertthat.selenium_shutterbug.utils.web.Browser.evaluate(Browser.java:281)
at com.assertthat.selenium_shutterbug.utils.web.Browser.takeScreenshotEntirePageUsingChromeCommand(Browser.java:187)
at com.assertthat.selenium_shutterbug.utils.web.Browser.takeScreenshotEntirePage(Browser.java:119)
at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:110)
at de.retest.web.ScreenshotProvider.shootFullPage(ScreenshotProvider.java:31)
at de.retest.web.ScreenshotProvider.shoot(ScreenshotProvider.java:26)
at de.retest.web.RecheckSeleniumAdapter.convert(RecheckSeleniumAdapter.java:74)
at …

Creating a screenshot is not so critical, so it shouldn't break the test

---

src/main/java/de/retest/web/RecheckSeleniumAdapter.java

By deleting the unused field (now part of `FrameConverter`).

Remove warning

---

src/main/java/de/retest/web/RecheckWebOptions.java
src/main/java/de/retest/web/selenium/AutocheckingRecheckDriver.java
src/main/java/de/retest/web/selenium/RecheckDriver.java

Just like `RecheckImpl` and `RecheckOptions` reside in the same package `de.retest.recheck`, `RecheckWebImpl` and `RecheckWebOptions` should do the same.

Move options to root package

---

pom.xml

See:
* http://branchandbound.net/blog/java/2017/12/automatic-module-name/
* https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html

Add automatic module name to manifest entries

---

CHANGELOG.md
src/main/java/de/retest/web/util/SeleniumWrapperUtil.java
src/test/java/de/retest/web/util/SeleniumWrapperUtilTest.java

since it causes Stackoverflow through loop if the same element is returned every time.
This is an issue when working with PageObjects (i.e. `@FindBy`) which do the evaluation of the actual element lazy (via [`Proxy`](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Proxy.html)) in `getWrapped`. Thus the construction of the PageObject is fine, until you access the object and its `WrapsElement` and a `NoSuchElementException` or similar is thrown.
However, the current implementation just silences this exception and instead returns the same element, which results in a recursion with no exit, and thus ultimately a `StackOverFlowError`.
This PR addresses this issue by rethrowing any potential exception from `getWrapped` with a `RuntimeException` and breaking the loop if the method …

Rethrow exception on getWrapped

---

src/main/java/de/retest/web/RecheckSeleniumAdapter.java

Since we create a snapshot of the whole website, we should scroll down
first, to trigger all sorts of loading mechanisms...

Scroll down to bottom

---

pom.xml

Update recheck version to 1.6.0-beta.1

---

src/main/java/de/retest/web/FrameConverter.java

As people might think we didn't get any data if there are no frames. Was a real question/concern...

Changed wording in logging from "Found 0 frame(s)" to "Found 0 sub-frame(s)"

---

.dependabot/config.yml

We do not want to have dependabot update the recheck version. This is done within the release process.
The [documentation](https://dependabot.com/docs/config-file/#ignored_updates) has followed and [verified](https://dependabot.com/docs/config-file/validator/), thus it *should* work, but for now as #493 has been closed, dependabot will not update the recheck version until the next release.
I want to test the the automatic assignment with this too.

Add recheck to the ignored updates

---

pom.xml

This reverts commit d764d03553479bdbae6825020c1b3db7e03f195f.
I always do the update branch on the wrong base initially. To avoid any accidental build failures, I revert this for now.
Please note that this is the **master** branch and not the *release* branch.

Revert "Bump recheck version to 1.9.0-beta.1"

---

pom.xml

~Due to some deploying errors, this is not available in central or github releases yet, and thus is provided through jitpack~ Travis finally decided to pass

Bumb recheck version to 1.9.0

---

pom.xml

This property can be set on demand via MVN_ARGS env variable.

Do not upload reports to rehub by default

---

src/test/java/de/retest/web/selenium/css/HasTest.java

Mockito 3.3.0 will complain about unused stubbings, which in this case seems like a bug. Converting this test into a parameterized test will work around this problem.
All done.
https://github.com/retest/recheck-web/pull/527 is currently broken due to a change in mockito.

Fix test for compatibility with mockito 3.3.0

---

CHANGELOG.md
src/main/java/de/retest/web/selenium/UnbreakableDriver.java

Provides an alias for `getWrappedDriver()` in oder to make usage for skipping checks more apparent.
There doesn't seem to be usage of `getWrappedDriver()` in the documentation so far, maybe an example should be added somewhere.
All done.

Add skipCheck() method to our drivers

---

CHANGELOG.md
src/main/java/de/retest/web/RecheckWebOptions.java

Override methods on the parent builder (`RecheckOptionsBuilder`) and always return an instance of `RecheckWebOptionsBuilder`.
There is a reference to the old behaviour in the documentation, I'll post a PR there shortly.

Always return instance of RecheckWebOptionsBuilder when building with it

---

pom.xml

TL;DR
Only change is setting the Jitpack version, so someone can use recheck-web with the latest recheck changes (i.e. metadata-ignore).

Update recheck-web using Jitpack

---

CHANGELOG.md
src/main/resources/javascript/getAllElementsByPath.js
src/test/resources/retest/recheck/de.retest.web.RecheckSeleniumAdapterIT/warnings_should_be_notified_properly_on_breaking_change.a.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.RecheckSeleniumAdapterIT/warnings_should_be_notified_properly_on_breaking_change.b.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.RecheckSeleniumAdapterIT/warnings_should_be_notified_properly_on_breaking_change.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.FormPageIT/form-page-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.FormPageIT/form-page-FirefoxDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-FirefoxDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/empty-article-FirefoxDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/findElement-equals-driver-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/findElement-equals-driver-FirefoxDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.ShowcaseIT/showcase-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.ShowcaseIT/showcase-FirefoxDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.00.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.01.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.02.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.03.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.04.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.05.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimplePageDiffIT/testSimpleChange.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimplePageIT/simple-page-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimplePageIT/simple-page-FirefoxDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleRecheckShowcaseIT/simpleShowcase.index.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerIT/special-container-ChromeDriver.click.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerIT/special-container-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerIT/special-container-FirefoxDriver.click.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerIT/special-container-FirefoxDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.TestHealerCssSelectorIT/setup.00.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.TestHealerCssSelectorIT/setup.01.recheck/retest.xml

This should make the detection more reliable, and solve problems with
rounded corners.
Earlier we tried to check if an element is covered by some other elements by checking of the corners are obscured. On rounded elements these corners may not exist. The check now tries to see of any of the middle-points on all four sides are obscured. This should also work with elliptic elements.
It may still turn out that there are edge cases that need to be handled, but for now this seems to work as intended.

Check sides instead of corners for isCovered

---

.retest/recheck.ignore
CHANGELOG.md
src/main/java/de/retest/web/selenium/AutocheckingRecheckDriver.java
src/main/java/de/retest/web/selenium/AutocheckingTargetLocator.java
src/test/java/de/retest/web/it/TabIT.java
src/test/java/de/retest/web/selenium/AutocheckingRecheckDriverTest.java
src/test/java/de/retest/web/selenium/AutocheckingTargetLocatorTest.java
src/test/resources/de/retest/web/it/page.html
src/test/resources/de/retest/web/it/tab.html
src/test/resources/retest/recheck/de.retest.web.it.TabIT/tab.00.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.TabIT/tab.01.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.TabIT/tab.02.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.TabIT/tab.03.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.TabIT/window.00.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.TabIT/window.01.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.TabIT/window.02.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.TabIT/window.03.recheck/retest.xml

> TL;DR Switching windows or tabs now create a proper check.
Since switching windows introduces a completely new context (similar to a `WebDriver#get`), we want to perform a check for that.
Similar to the other `Autochecking...` implementations, the introduced `AutocheckingTargetLocator` will perform a check with an artificial name to be used by the `AutocheckingNamingStrategy` after the action in question has been performed, to allow for the new context to be captured.
1. I am not sure, what other methods need a check, since it is important, in which context the script is executed. However, based on the `EventFiringTargetLocator` I assume that only the windows needs such checks, but I will need to do some testing for that.
1. I am assuming that …

Perform a check when switching windows

---

src/test/resources/retest/recheck/de.retest.web.it.FormPageIT/form-page-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/findElement-equals-driver-ChromeDriver.open.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.00.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.01.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.02.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.03.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.04.recheck/retest.xml
src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.05.recheck/retest.xml

Apparently, I have used a snapshot version of review. But that should not be a problem.
*And again, no metadata changes. Really need to look into that...*

Update Golden Masters to include a reset for outline-offset

---

CHANGELOG.md
src/main/java/de/retest/web/selenium/AutocheckingWebElement.java
src/test/java/de/retest/web/selenium/AutocheckingWebElementIT.java
src/test/java/de/retest/web/selenium/AutocheckingWebElementTest.java

> TL;DR This fixes unchecked casting within the Actions API.
This is related to RET-2071.
Apparently, the Actions API does some unchecked casting. When using any instance of `AutocheckingDriver` will cause this exception.
```
Actions builder = new Actions(driver);
builder.moveToElement(element).perform();
```
But, as the integration test shows, the actual method `Locatable#getCoordinates` is never called, but I added a sensible implementation and test for that. Since I need an actual browser for the implementation (because there is some weird stuff going on in the background), I made sure that no Golden Masters are created&mdash;to have the test pass and because they are not important in this context.
The test failures are related to #627 and …

Allow AutocheckingWebElement to implement Locatable

---

.github/workflows/build.yml

Finally I can get rid of this. 😉
PS: https://community.sonarsource.com/t/sonarcloud-knows-how-to-scan-your-java-14-code/28410
PPS: You have to update your SonarCloud token.

Run tests with newest JDK 14
